#pragma config(Sensor, in1,    angle1,         sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define Arm_motor port2

#define Kp 400                   //상수
#define Ki 100 
#define Kd 100
#define deltaT 0.001 //1millisec

const double ideal=2048;             //130도
double currentval;
double err, preverr;
double err_i, err_D;
double Kpterm, Kiterm, Kdterm;
double ctrl;

int limit(int x)              //모터속도제한
{
	if(x<-127)
		return -127;
	else if(x>127)
		return 127;
	else
		return x;
}

task main()
{
	for(;;)
	{
  currentval=SensorValue[angle1];	

  err = ideal - currentval;

	Kpterm = Kp * err;

	err_i += err * deltaT;
	Kiterm = Ki * err_i;

	err_D = (err - preverr) / deltaT;
	Kdterm = Kd*err_D;

	preverr = err;
	ctrl = Kpterm + Kiterm + Kdterm;
	
	motor[Arm_motor]=limit(ctrl);
	}
}
